baseurl = "nokaze.github.io"
languageCode = "en-us"
title = "nokaze Blog"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10
disqusShortname = "nokaze"

[author]
    name = "nokaze"

[permalinks]
    post = "/blog/:slug/"

[taxonomies]
    category = "categories"

[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    # truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "nokaze Blog"
    defaultKeywords = "programming"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"
    # highlight = "solarized_dark"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    # tagline = "Your favourite quote or soundbite."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    # home = "Blog"

    # Metadata used to drive integrations.
    # googleAuthorship = "Your Google+ profile ID"
    # googleAnalytics = "Your Google Analytics tracking code"
    # gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/nokaze"
    # bitbucket = ""
    # linkedin = ""
    # googleplus = ""
    # facebook = ""
    twitter = "https://twitter.com/nkz_bw"
    # youtube = ""

    # Other social-like sidebar links
    # rss = false  # switch to true to enable RSS icon link

    # flattr = ""  # populate with your flattr uid
